ImageApprovalStatus updated
stefanj122/Fotodesk pull request #15
Opened 2023-02-28 18:56 UTC by milosst94

2023-03-02 17:00 UTC, Branimir requested changes

2023-03-02 17:00 UTC, Branimir commented on src/images/images.controller.ts
> +  @Put()
This should be a specific route

2023-03-02 17:00 UTC, Branimir commented on src/images/images.service.ts
> +  async updateImageApprovalStatus(@Body() imagesData: { id: number; isApproved: boolean }[]){
This should be just a variable, not from body

2023-03-02 17:00 UTC, Branimir commented on src/images/images.controller.ts
> +    await this.imagesService.updateImageApprovalStatus(imagesData)
What do we return?

2023-03-02 17:05 UTC, stefanj122 commented on src/images/images.service.ts
> +    await Promise.all(arrOfPromises);
Here you can do try, catch on this promises.

2023-03-04 11:50 UTC, Branimir requested changes

2023-03-04 11:50 UTC, Branimir commented on src/images/images.controller.ts
> +  @Put('images/Approval')
Why Capital A? :)

2023-03-04 11:50 UTC, Branimir commented on src/images/images.service.ts
> +      return BadRequestException;
We need to "throw" exception - return will give 200 response code, which is not good for FE developers

2023-03-07 17:31 UTC, Branimir approved these changes

2023-03-07 17:38 UTC, Branimir approved these changes

2023-03-09 16:37 UTC, closed without merging