Image approve
stefanj122/Fotodesk pull request #35
Opened 2023-09-26 16:53 UTC by mickotomic

Refactor mail helper, winston legger,  upload images notification and implementation of mail sending on image approval.

2023-09-28 15:41 UTC, milosst94 commented on src/helpers/emailSender.helper.ts
file naming is not appropriate, instead of this naming format , we should be using kebab case

2023-09-28 16:15 UTC, Branimir requested changes

2023-09-28 16:15 UTC, Branimir commented on src/admin/images/images.service.ts
> +    private mailerService: MailerService,
Is this needed?

2023-09-28 16:15 UTC, Branimir commented on src/admin/images/images.service.ts
Can we refactor this on line 115? This line: this.em.emit('image.uploaded', photo);

This send an email to the admin user for each uploaded image in this context. It would be much better if we send only one email to the admins that would contain all uploaded images (their links). This means changing the template too.

2023-10-17 15:41 UTC, Branimir approved these changes

2023-11-16 14:52 UTC, merged